# Generated by Django 3.2.5 on 2021-07-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_url', models.URLField(max_length=1000)),
                ('short_url', models.URLField(max_length=100)),
            ],
        ),
    ]
